<?php

return [
    'playlist_max_bytes' => (int) env('IPTV_PLAYLIST_MAX_BYTES', 8 * 1024 * 1024),
    'playlist_max_channels' => (int) env('IPTV_PLAYLIST_MAX_CHANNELS', 10000),
    'xmltv_max_bytes' => (int) env('IPTV_XMLTV_MAX_BYTES', 8 * 1024 * 1024),
    'xtream_xmltv_max_bytes' => (int) env('IPTV_XTREAM_XMLTV_MAX_BYTES', 128 * 1024 * 1024),
    'xmltv_max_channels' => (int) env('IPTV_XMLTV_MAX_CHANNELS', 50000),
    'xmltv_max_programs' => (int) env('IPTV_XMLTV_MAX_PROGRAMS', 100000),
    'xtream_xmltv_max_programs_scanned' => (int) env('IPTV_XTREAM_XMLTV_MAX_PROGRAMS_SCANNED', 1000000),
    'xtream_xmltv_programs_per_channel' => (int) env('IPTV_XTREAM_XMLTV_PROGRAMS_PER_CHANNEL', 24),
    'xtream_xmltv_horizon_hours' => (int) env('IPTV_XTREAM_XMLTV_HORIZON_HOURS', 24),
    'provider_guide_max_rows' => (int) env('IPTV_PROVIDER_GUIDE_MAX_ROWS', 100000),
    'connect_timeout_seconds' => (int) env('IPTV_CONNECT_TIMEOUT_SECONDS', 5),
    'request_timeout_seconds' => (int) env('IPTV_REQUEST_TIMEOUT_SECONDS', 20),
    'stream_timeout_seconds' => (int) env('IPTV_STREAM_TIMEOUT_SECONDS', 45),
    'manifest_max_bytes' => (int) env('IPTV_MANIFEST_MAX_BYTES', 2 * 1024 * 1024),
    'resource_url_max_bytes' => (int) env('IPTV_RESOURCE_URL_MAX_BYTES', 8192),
    'manifest_max_resources' => (int) env('IPTV_MANIFEST_MAX_RESOURCES', 256),
    'manifest_max_origins' => (int) env('IPTV_MANIFEST_MAX_ORIGINS', 16),
    'playback_max_resources' => (int) env('IPTV_PLAYBACK_MAX_RESOURCES', 2048),
    'playback_max_attempts' => (int) env('IPTV_PLAYBACK_MAX_ATTEMPTS', 100),
    'playback_max_redirects' => (int) env('IPTV_PLAYBACK_MAX_REDIRECTS', 2),
    'playlist_max_depth' => (int) env('IPTV_PLAYLIST_MAX_DEPTH', 6),
    'api_max_response_bytes' => (int) env('IPTV_API_MAX_RESPONSE_BYTES', 8 * 1024 * 1024),
    'category_max_rows' => (int) env('IPTV_CATEGORY_MAX_ROWS', 5000),
    'channel_max_rows' => (int) env('IPTV_CHANNEL_MAX_ROWS', 10000),
    'guide_channel_limit' => (int) env('IPTV_GUIDE_CHANNEL_LIMIT', 20),
    'guide_program_limit' => (int) env('IPTV_GUIDE_PROGRAM_LIMIT', 4),
    'playback_lease_seconds' => (int) env('IPTV_PLAYBACK_LEASE_SECONDS', 90),
    'playback_session_concurrency' => (int) env('IPTV_PLAYBACK_SESSION_CONCURRENCY', 6),
    'playback_provider_concurrency' => (int) env('IPTV_PLAYBACK_PROVIDER_CONCURRENCY', 48),
    'playback_request_lease_seconds' => (int) env('IPTV_PLAYBACK_REQUEST_LEASE_SECONDS', 75),
    'playback_stream_max_seconds' => (int) env('IPTV_PLAYBACK_STREAM_MAX_SECONDS', 60),
    'provider_max_connections' => (int) env('IPTV_PROVIDER_MAX_CONNECTIONS', 1),
];
